definitions:
  structs.Post:
    properties:
      author:
        type: string
      content:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/import:
    post:
      consumes:
      - multipart/form-data
      description: Upload and import posts from a JSON file
      parameters:
      - description: JSON file with posts
        in: formData
        name: file
        required: true
        type: file
      produces:
      - text/plain
      responses:
        "200":
          description: Posts imported successfully
          schema:
            type: string
        "400":
          description: Error retrieving the file
          schema:
            type: string
        "500":
          description: Error decoding JSON file
          schema:
            type: string
      summary: Import posts from a JSON file
      tags:
      - Admin API
  /post:
    delete:
      consumes:
      - application/json
      description: Delete a post by ID
      parameters:
      - description: Post ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Post not found
          schema:
            type: string
      summary: Delete a post by ID
      tags:
      - Post API
    get:
      consumes:
      - application/json
      description: Get a post by ID
      parameters:
      - description: Post ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Post'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Post not found
          schema:
            type: string
      summary: Get a post by ID
      tags:
      - Post API
    post:
      consumes:
      - application/json
      description: Create a new blog post
      parameters:
      - description: Post content
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/structs.Post'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/structs.Post'
      summary: Create a new post
      tags:
      - Post API
    put:
      consumes:
      - application/json
      description: Update a post by ID
      parameters:
      - description: Post ID
        in: query
        name: id
        required: true
        type: integer
      - description: Post content
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/structs.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.Post'
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: Post not found
          schema:
            type: string
      summary: Update a post by ID
      tags:
      - Post API
  /posts:
    get:
      consumes:
      - application/json
      description: List all blog posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structs.Post'
            type: array
      summary: List all posts
      tags:
      - Post API
swagger: "2.0"
